Traceback (most recent call last):
  File "/home/pbellec/env/psy3018/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/pbellec/env/psy3018/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/pbellec/env/psy3018/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/pbellec/env/psy3018/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/pbellec/env/psy3018/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/pbellec/env/psy3018/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/pbellec/env/psy3018/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# activation related to a mental computation task, as opposed to narrative sentence reading/listening
# librairies
from nilearn import datasets
import pandas as pd
from nilearn.glm import threshold_stats_img, SecondLevelModel
from nilearn import plotting

n_samples = 20
localizer_dataset = datasets.fetch_localizer_calculation_task(
    n_subjects=n_samples)
cmap_filenames = localizer_dataset.cmaps

design_matrix = pd.DataFrame([1] * n_samples, columns=['intercept'])

#z_map = second_level_model.compute_contrast(output_type='z_score')

#thresholded_map1, threshold1 = threshold_stats_img(
#    z_map, alpha=.05, height_control='fdr', cluster_threshold=10)

# visualiser
# sans seuil
#display = plotting.plot_stat_map(z_map, title='Carte activation')

# avec seuil
#plotting.plot_stat_map(
#    thresholded_map1, cut_coords=display.cut_coords, threshold=threshold1,
#    title='Carte activation avec seuil, fdr <.05')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
[0;32m<ipython-input-4-902ea1378e79>[0m in [0;36m<module>[0;34m[0m
[1;32m      3[0m [0;32mfrom[0m [0mnilearn[0m [0;32mimport[0m [0mdatasets[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;32mimport[0m [0mpandas[0m [0;32mas[0m [0mpd[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 5[0;31m [0;32mfrom[0m [0mnilearn[0m[0;34m.[0m[0mglm[0m [0;32mimport[0m [0mthreshold_stats_img[0m[0;34m,[0m [0mSecondLevelModel[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      6[0m [0;32mfrom[0m [0mnilearn[0m [0;32mimport[0m [0mplotting[0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m [0;34m[0m[0m

[0;31mImportError[0m: cannot import name 'SecondLevelModel' from 'nilearn.glm' (/home/pbellec/env/psy3018/lib/python3.8/site-packages/nilearn/glm/__init__.py)
ImportError: cannot import name 'SecondLevelModel' from 'nilearn.glm' (/home/pbellec/env/psy3018/lib/python3.8/site-packages/nilearn/glm/__init__.py)

